//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bot1350.DBServises
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishId { get; set; }
        public int UserId { get; set; }
        public string Wish { get; set; }
    
        public virtual User User { get; set; }
    }
}
